services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.server-sim
    container_name: ecommerce-sim
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_URL: jdbc:postgresql://ecommerce-db:5432/ecommercedb
      DB_USER: ecommerceuser
      DB_PASSWORD: ecommercepass
      REDIS_HOST: ecommerce-redis
      REDIS_PORT: 6379
      JAVA_TOOL_OPTIONS: >-
        -Xms256m -Xmx512m
        -XX:+UseG1GC
        -XX:MaxGCPauseMillis=100
        -XX:ActiveProcessorCount=1
        -Djava.security.egd=file:/dev/./urandom
    # Límites reales para Docker standalone
    cpus: '1.0'
    mem_limit: 768m
    ports:
      - "9090:8090"
    depends_on:
      - ecommerce-db
      - ecommerce-redis
    networks:
      - ecommerce-net

  ecommerce-db:
    image: postgres:16-alpine
    container_name: ecommerce-sim-db
    environment:
      POSTGRES_DB: ecommercedb
      POSTGRES_USER: ecommerceuser
      POSTGRES_PASSWORD: ecommercepass
    command: postgres -c max_connections=100
    volumes:
      - ecommerce_sim_pgdata:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
    networks:
      - ecommerce-net

  ecommerce-redis:
    image: redis:7-alpine
    container_name: ecommerce-sim-redis
    command: redis-server --maxmemory 64mb --maxmemory-policy allkeys-lru --save ""
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 96M
    networks:
      - ecommerce-net

volumes:
  ecommerce_sim_pgdata:

networks:
  ecommerce-net:
    driver: bridge
