Args = --no-fallback \
       -H:+ReportExceptionStackTraces \
       --initialize-at-build-time=org.slf4j,ch.qos.logback \
       -H:IncludeResources=.*/application.*\\.yml \
       -H:IncludeResources=.*/db/migration/.*\\.sql \
       -H:IncludeResources=.*/templates/.*\\.html \
       -H:IncludeResources=.*/logback.*\\.xml
